### ISSUE TITLE
Version 2.18.0 not working with ESP32

### ISSUE THREAD

**Issue by Arbee72** [mongoose-os/mos#38]
Any prior successful build for ESP32 platform in ver. 2.18.0 fails with the error:
    
App size: 1584288 of 1572864 (100%)
App is too big
make: *** [app-bin-check] Error 1_

**Comment by rojer** [comment]
size increased due to multicore support being enabled by default.
looks like your app will need to stay unicore. turn off multicore support by setting an IDF option:

```yaml
build_vars:
  ESP_IDF_SDKCONFIG_OPTS: >
    ${build_vars.ESP_IDF_SDKCONFIG_OPTS}
    CONFIG_FREERTOS_UNICORE=y
```
